var loadVosklet = (() => {
  var _scriptName = typeof document != 'undefined' ? document.currentScript?.src : undefined;
  
  return (
async function(moduleArg = {}) {
  var moduleRtn;

var n=moduleArg,aa,ba,ca=new Promise((a,b)=>{aa=a;ba=b}),da="object"==typeof window,ea="undefined"!=typeof WorkerGlobalScope,fa=!!n.$ww;
if(da){var p=[],ha=["status","partialResult","result"];let a=caches.open("Vosklet"),b=URL.createObjectURL(new Blob(["(",(()=>{registerProcessor("VoskletTransferer",class extends AudioWorkletProcessor{constructor(e){super();this.pa=0;this.xa=e.processorOptions[0];this.ua=new Float32Array(this.xa)}process(e){e[0][0]&&(this.ua.set(e[0][0],this.pa),this.pa+=128,this.pa>=this.xa&&(this.pa=0,this.port.postMessage(this.ua,[this.ua.buffer]),this.ua=new Float32Array(this.xa)));return!0}})}).toString(),")()"],
{type:"text/javascript"}));class c extends EventTarget{constructor(){super();p.push(this)}delete(){this.ea.delete()}static async oa(e,f,g,h){let k=new c,m=new Promise((q,v)=>{k.addEventListener("status",t=>{t.detail?v(t.detail):(h&&(k.findWord=z=>k.ea.findWord(z)),q(k))},{once:!0})});var l=await caches.open("Vosklet");const r=(await l.keys()).find(q=>q.url.split("?")[1]===g);if(r)e=await l.match(r);else{e=await fetch(e,{cache:"no-store"});if(!e.ok)throw"Unable to fetch model, status: "+e.status;await l.put(`${f}?${g}`,
e.clone())}f=await (new Response(e.body.pipeThrough(new DecompressionStream("gzip")))).arrayBuffer();l=u(f.byteLength);w().set(new Uint8Array(f),l);k.ea=new n.CommonModel(p.length-1,h,l,f.byteLength);return m}}class d extends EventTarget{constructor(){super();this.acceptWaveform=e=>{let f=u(4*e.length);ia().set(e,f/4);this.ea.acceptWaveform(f,e.length)};p.push(this);return new Proxy(this,{get(e,f){if(void 0!=e[f]||void 0!=e.ea[f]){var g=e[f];if(g)return g.bind?g.bind(e):g;g=e.ea[f];return g.bind?
g.bind(e.ea):g}}})}async delete(e=!1){let f=new Promise(g=>this.addEventListener("status",()=>{this.ea.delete();g()},{once:!0}));this.ea.safeDelete(e);return f}static async oa(e,f,g,h,k){let m=new d,l=new Promise((r,q)=>{m.addEventListener("status",v=>{v.detail?q(v.detail):r(m)},{once:!0})});switch(g){case 1:m.ea=new n.Recognizer(p.length-1,f,e);break;case 2:m.ea=new n.Recognizer(p.length-1,f,e,k);break;default:m.ea=new n.Recognizer(p.length-1,f,e,h,0)}return l}}n={getModelCache:()=>a,cleanUp:async()=>
{for(let e of p)await e.delete();URL.revokeObjectURL(b)},createTransferer:async(e,f)=>{await e.audioWorklet.addModule(b);return new AudioWorkletNode(e,"VoskletTransferer",{channelCountMode:"explicit",numberOfInputs:1,numberOfOutputs:0,channelCount:1,processorOptions:[f]})},createModel:(e,f,g)=>c.oa(e,f,g,!0),createSpkModel:(e,f,g)=>c.oa(e,f,g,!1),createRecognizer:(e,f)=>d.oa(e.ea,f,1),createRecognizerWithGrm:(e,f,g)=>d.oa(e.ea,f,3,g,null),createRecognizerWithSpkModel:(e,f,g)=>d.oa(e.ea,f,2,null,g.ea)}}
var x="",ja,ka;
if(da||ea)ea?x=self.location.href:"undefined"!=typeof document&&document.currentScript&&(x=document.currentScript.src),_scriptName&&(x=_scriptName),x.startsWith("blob:")?x="":x=x.slice(0,x.replace(/[?#].*/,"").lastIndexOf("/")+1),ea&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ja=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};
var la=console.log.bind(console),y=console.error.bind(console),A,ma,na=!1,B,oa,pa,qa,ra,sa,ta,ua,va,wa;function xa(){A.buffer!=B.buffer&&C();return B}function w(){A.buffer!=B.buffer&&C();return oa}function ya(){A.buffer!=B.buffer&&C();return pa}function za(){A.buffer!=B.buffer&&C();return qa}function D(){A.buffer!=B.buffer&&C();return ra}function F(){A.buffer!=B.buffer&&C();return sa}function ia(){A.buffer!=B.buffer&&C();return ta}
function C(){var a=A.buffer;B=new Int8Array(a);pa=new Int16Array(a);oa=new Uint8Array(a);qa=new Uint16Array(a);ra=new Int32Array(a);sa=new Uint32Array(a);ta=new Float32Array(a);wa=new Float64Array(a);ua=new BigInt64Array(a);va=new BigUint64Array(a)}function Aa(){if(fa){let a=n;Ba(a.sb,a.sz);removeEventListener("message",Ca);Da=Da.forEach(Ea);addEventListener("message",Ea)}else G.V()}var H=0,I=null;
function Fa(a){a="Aborted("+a+")";y(a);na=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}var Ga;async function Ha(a){try{var b=await ja(a);return new Uint8Array(b)}catch{}if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function Ia(a,b){try{var c=await Ha(a);return await WebAssembly.instantiate(c,b)}catch(d){y(`failed to asynchronously prepare wasm: ${d}`),Fa(d)}}
async function Ja(a){var b=Ga;if("function"==typeof WebAssembly.instantiateStreaming)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){y(`wasm streaming compile failed: ${d}`),y("falling back to ArrayBuffer instantiation")}return Ia(b,a)}class Ka{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Da=[],La=a=>{if(!na)try{a()}catch(b){if(!(b instanceof Ka||"unwind"==b))throw b;}},Oa=[],Pa,Qa=a=>{var b=Oa[a];b||(Oa[a]=b=Pa.get(a));return b},Ea=a=>{let b=a.data,c=b._wsc;c&&La(()=>Qa(c)(...b.x))},Ca=a=>{Da.push(a)},Ra=new TextDecoder,J=(a,b)=>{if(!a)return"";b=a+b;for(var c=a;!(c>=b)&&w()[c];)++c;return Ra.decode(w().slice(a,c))};class Sa{constructor(a){this.ca=a-24}}
var Ta=0,Ua=0,Va=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a},Wa,K=a=>{for(var b="";w()[a];)b+=Wa[w()[a++]];return b},L={},M={},Xa={},N=n.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}},Ya=a=>{throw new N(a);};
function Za(a,b,c={}){var d=b.name;if(!a)throw new N(`type "${d}" must have a positive integer typeid pointer`);if(M.hasOwnProperty(a)){if(c.Ha)return;throw new N(`Cannot register type '${d}' twice`);}M[a]=b;delete Xa[a];L.hasOwnProperty(a)&&(b=L[a],delete L[a],b.forEach(e=>e()))}function O(a,b,c={}){return Za(a,b,c)}
var $a=(a,b,c)=>{switch(b){case 1:return c?d=>xa()[d]:d=>w()[d];case 2:return c?d=>ya()[d>>1]:d=>za()[d>>1];case 4:return c?d=>D()[d>>2]:d=>F()[d>>2];case 8:return c?d=>ua[d>>3]:d=>va[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},ab=a=>{throw new N(a.aa.da.ba.name+" instance already deleted");},bb=!1,cb=()=>{},P=a=>{if("undefined"===typeof FinalizationRegistry)return P=b=>b,a;bb=new FinalizationRegistry(b=>{b=b.aa;--b.count.value;0===b.count.value&&(b.ga?b.ja.la(b.ga):
b.da.ba.la(b.ca))});P=b=>{var c=b.aa;c.ga&&bb.register(b,{aa:c},b);return b};cb=b=>{bb.unregister(b)};return P(a)},db=[];function eb(){}
var fb=(a,b)=>Object.defineProperty(b,"name",{value:a}),gb={},hb=(a,b,c)=>{if(void 0===a[b].fa){var d=a[b];a[b]=function(...e){if(!a[b].fa.hasOwnProperty(e.length))throw new N(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].fa})!`);return a[b].fa[e.length].apply(this,e)};a[b].fa=[];a[b].fa[d.qa]=d}},ib=(a,b,c)=>{if(n.hasOwnProperty(a)){if(void 0===c||void 0!==n[a].fa&&void 0!==n[a].fa[c])throw new N(`Cannot register public name '${a}' twice`);hb(n,
a,a);if(n[a].fa.hasOwnProperty(c))throw new N(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);n[a].fa[c]=b}else n[a]=b,n[a].qa=c},jb=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function kb(a,b,c,d,e,f,g,h){this.name=a;this.constructor=b;this.na=c;this.la=d;this.ha=e;this.Fa=f;this.ta=g;this.Da=h;this.Ja=[]}
var lb=(a,b,c)=>{for(;b!==c;){if(!b.ta)throw new N(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.ta(a);b=b.ha}return a};function mb(a,b){if(null===b){if(this.ya)throw new N(`null is not a valid ${this.name}`);return 0}if(!b.aa)throw new N(`Cannot pass "${Va(b)}" as a ${this.name}`);if(!b.aa.ca)throw new N(`Cannot pass deleted object as a pointer of type ${this.name}`);return lb(b.aa.ca,b.aa.da.ba,this.ba)}
function nb(a,b){if(null===b){if(this.ya)throw new N(`null is not a valid ${this.name}`);if(this.wa){var c=this.Ka();null!==a&&a.push(this.la,c);return c}return 0}if(!b||!b.aa)throw new N(`Cannot pass "${Va(b)}" as a ${this.name}`);if(!b.aa.ca)throw new N(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.va&&b.aa.da.va)throw new N(`Cannot convert argument of type ${b.aa.ja?b.aa.ja.name:b.aa.da.name} to parameter type ${this.name}`);c=lb(b.aa.ca,b.aa.da.ba,this.ba);if(this.wa){if(void 0===
b.aa.ga)throw new N("Passing raw pointer to smart pointer is illegal");switch(this.Ma){case 0:if(b.aa.ja===this)c=b.aa.ga;else throw new N(`Cannot convert argument of type ${b.aa.ja?b.aa.ja.name:b.aa.da.name} to parameter type ${this.name}`);break;case 1:c=b.aa.ga;break;case 2:if(b.aa.ja===this)c=b.aa.ga;else{var d=b.clone();c=this.La(c,ob(()=>d["delete"]()));null!==a&&a.push(this.la,c)}break;default:throw new N("Unsupporting sharing policy");}}return c}
function pb(a,b){if(null===b){if(this.ya)throw new N(`null is not a valid ${this.name}`);return 0}if(!b.aa)throw new N(`Cannot pass "${Va(b)}" as a ${this.name}`);if(!b.aa.ca)throw new N(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.aa.da.va)throw new N(`Cannot convert argument of type ${b.aa.da.name} to parameter type ${this.name}`);return lb(b.aa.ca,b.aa.da.ba,this.ba)}function qb(a){return this.fromWireType(F()[a>>2])}
var rb=(a,b,c)=>{if(b===c)return a;if(void 0===c.ha)return null;a=rb(a,b,c.ha);return null===a?null:c.Da(a)},sb={},tb=(a,b)=>{if(void 0===b)throw new N("ptr should not be undefined");for(;a.ha;)b=a.ta(b),a=a.ha;return sb[b]},ub=n.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}},vb=(a,b)=>{if(!b.da||!b.ca)throw new ub("makeClassHandle requires ptr and ptrType");if(!!b.ja!==!!b.ga)throw new ub("Both smartPtrType and smartPtr must be specified");b.count={value:1};
return P(Object.create(a,{aa:{value:b,writable:!0}}))};function wb(a,b,c,d,e,f,g,h,k,m,l){this.name=a;this.ba=b;this.ya=c;this.va=d;this.wa=e;this.Ia=f;this.Ma=g;this.Ba=h;this.Ka=k;this.La=m;this.la=l;e||void 0!==b.ha?this.toWireType=nb:(this.toWireType=d?mb:pb,this.ia=null)}
var xb=(a,b,c)=>{if(!n.hasOwnProperty(a))throw new ub("Replacing nonexistent public symbol");void 0!==n[a].fa&&void 0!==c?n[a].fa[c]=b:(n[a]=b,n[a].qa=c)},Q=(a,b)=>{a=K(a);var c=Qa(b);if("function"!=typeof c)throw new N(`unknown function pointer with signature ${a}: ${b}`);return c};class zb extends Error{}
var Bb=a=>{a=Ab(a);var b=K(a);R(a);return b},Cb=(a,b)=>{function c(f){e[f]||M[f]||(Xa[f]?Xa[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new zb(`${a}: `+d.map(Bb).join([", "]));},S=(a,b,c)=>{function d(h){h=c(h);if(h.length!==a.length)throw new ub("Mismatched type converter count");for(var k=0;k<a.length;++k)O(a[k],h[k])}a.forEach(h=>Xa[h]=b);var e=Array(b.length),f=[],g=0;b.forEach((h,k)=>{M.hasOwnProperty(h)?e[k]=M[h]:(f.push(h),L.hasOwnProperty(h)||(L[h]=[]),L[h].push(()=>
{e[k]=M[h];++g;g===f.length&&d(e)}))});0===f.length&&d(e)},Db=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(F()[b+4*d>>2]);return c},Eb=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function Fb(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].ia)return!0;return!1}
function Gb(a,b,c,d,e,f){var g=b.length;if(2>g)throw new N("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,k=Fb(b);c="void"!==b[0].name;d=[a,Ya,d,e,Eb,b[0],b[1]];for(e=0;e<g-2;++e)d.push(b[e+2]);if(!k)for(e=h?1:2;e<b.length;++e)null!==b[e].ia&&d.push(b[e].ia);k=Fb(b);e=b.length-2;var m=[],l=["fn"];h&&l.push("thisWired");for(g=0;g<e;++g)m.push(`arg${g}`),l.push(`arg${g}Wired`);m=m.join(",");l=l.join(",");m=`return function (${m}) {\n`;k&&
(m+="var destructors = [];\n");var r=k?"destructors":"null",q="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");h&&(m+=`var thisWired = classParam['toWireType'](${r}, this);\n`);for(g=0;g<e;++g)m+=`var arg${g}Wired = argType${g}['toWireType'](${r}, arg${g});\n`,q.push(`argType${g}`);m+=(c||f?"var rv = ":"")+`invoker(${l});\n`;if(k)m+="runDestructors(destructors);\n";else for(g=h?1:2;g<b.length;++g)f=1===g?"thisWired":"arg"+(g-2)+"Wired",null!==b[g].ia&&(m+=`${f}_dtor(${f});\n`,
q.push(`${f}_dtor`));c&&(m+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");let [v,t]=[q,m+"}\n"];b=(new Function(...v,t))(...d);return fb(a,b)}
for(var Hb=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},Ib=[],T=[],ob=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Ib.pop()||T.length;T[b]=a;T[b+1]=1;return b}},Jb={name:"emscripten::val",fromWireType:a=>{if(!a)throw new N(`Cannot use deleted val. handle = ${a}`);var b=T[a];9<a&&0===--T[a+1]&&(T[a]=void 0,Ib.push(a));return b},toWireType:(a,b)=>ob(b),ka:8,readValueFromPointer:qb,ia:null},Kb=(a,b,c)=>{switch(b){case 1:return c?
function(d){return this.fromWireType(xa()[d])}:function(d){return this.fromWireType(w()[d])};case 2:return c?function(d){return this.fromWireType(ya()[d>>1])}:function(d){return this.fromWireType(za()[d>>1])};case 4:return c?function(d){return this.fromWireType(D()[d>>2])}:function(d){return this.fromWireType(F()[d>>2])};default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Lb=a=>{var b=M[a];if(void 0===b)throw a=`${"enum"} has unknown type ${Bb(a)}`,new N(a);return b},Mb=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(ia()[c>>
2])};case 8:return function(c){var d=this.fromWireType;A.buffer!=B.buffer&&C();return d.call(this,wa[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Nb=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var h=a.charCodeAt(++f);g=65536+((g&1023)<<10)|h&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;
b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e},U=(a,b,c)=>Nb(a,w(),b,c),V=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Ob=new TextDecoder("utf-16le"),Pb=(a,b)=>{var c=a>>1;for(b=c+b/2;!(c>=b)&&za()[c];)++c;c<<=1;return Ob.decode(w().slice(a,c))},Qb=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e){var f=a.charCodeAt(e);
ya()[b>>1]=f;b+=2}ya()[b>>1]=0;return b-d},Rb=a=>2*a.length,Sb=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=D()[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},Tb=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var g=a.charCodeAt(++e);f=65536+((f&1023)<<10)|g&1023}D()[b>>2]=f;b+=4;if(b+4>c)break}D()[b>>2]=0;return b-d},Ub=a=>{for(var b=
0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},Vb={},Wb=1,Xb=URL.createObjectURL(new Blob(["onmessage=function(d){onmessage=null;d=d.data;d[`instantiateWasm`]=(i,r)=>{var n=new WebAssembly.Instance(d[`wasm`],i);return r(n,d[`wasm`]);};importScripts(d.js);loadVosklet(d);d.wasm=d.mem=d.js=0;}"],{type:"application/javascript"})),W={},Yb=[],Z=[],Zb=[],$b={},bc=()=>{if(!ac){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==
typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:"./this.program"},b;for(b in $b)void 0===$b[b]?delete a[b]:a[b]=$b[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);ac=c}return ac},ac,cc=()=>a=>a.set(crypto.getRandomValues(new Uint8Array(a.byteLength))),dc=a=>{(dc=cc())(a)},ec=Array(256),fc=0;256>fc;++fc)ec[fc]=String.fromCharCode(fc);Wa=ec;
(()=>{let a=eb.prototype;Object.assign(a,{isAliasOf:function(c){if(!(this instanceof eb&&c instanceof eb))return!1;var d=this.aa.da.ba,e=this.aa.ca;c.aa=c.aa;var f=c.aa.da.ba;for(c=c.aa.ca;d.ha;)e=d.ta(e),d=d.ha;for(;f.ha;)c=f.ta(c),f=f.ha;return d===f&&e===c},clone:function(){this.aa.ca||ab(this);if(this.aa.sa)return this.aa.count.value+=1,this;var c=P,d=Object,e=d.create,f=Object.getPrototypeOf(this),g=this.aa;c=c(e.call(d,f,{aa:{value:{count:g.count,ra:g.ra,sa:g.sa,ca:g.ca,da:g.da,ga:g.ga,ja:g.ja}}}));
c.aa.count.value+=1;c.aa.ra=!1;return c},["delete"](){this.aa.ca||ab(this);if(this.aa.ra&&!this.aa.sa)throw new N("Object already scheduled for deletion");cb(this);var c=this.aa;--c.count.value;0===c.count.value&&(c.ga?c.ja.la(c.ga):c.da.ba.la(c.ca));this.aa.sa||(this.aa.ga=void 0,this.aa.ca=void 0)},isDeleted:function(){return!this.aa.ca},deleteLater:function(){this.aa.ca||ab(this);if(this.aa.ra&&!this.aa.sa)throw new N("Object already scheduled for deletion");db.push(this);this.aa.ra=!0;return this}});
const b=Symbol.dispose;b&&(a[b]=a["delete"])})();
Object.assign(wb.prototype,{Ga(a){this.Ba&&(a=this.Ba(a));return a},Aa(a){this.la?.(a)},ka:8,readValueFromPointer:qb,fromWireType:function(a){function b(){return this.wa?vb(this.ba.na,{da:this.Ia,ca:c,ja:this,ga:a}):vb(this.ba.na,{da:this,ca:a})}var c=this.Ga(a);if(!c)return this.Aa(a),null;var d=tb(this.ba,c);if(void 0!==d){if(0===d.aa.count.value)return d.aa.ca=c,d.aa.ga=a,d.clone();d=d.clone();this.Aa(a);return d}d=this.ba.Fa(c);d=gb[d];if(!d)return b.call(this);d=this.va?d.Ca:d.pointerType;var e=
rb(c,this.ba,d.ba);return null===e?b.call(this):this.wa?vb(d.ba.na,{da:d,ca:e,ja:this,ga:a}):vb(d.ba.na,{da:d,ca:e})}});T.push(0,1,void 0,1,null,1,!0,1,!1,1);n.count_emval_handles=()=>T.length/2-5-Ib.length;fa&&(Vb[0]=this,addEventListener("message",Ca));n.wasmMemory?A=n.wasmMemory:A=new WebAssembly.Memory({initial:5040,maximum:32768,shared:!0});C();function gc(a,b,c){da?p[a].dispatchEvent(new CustomEvent(ha[b],{detail:0==c?null:J(c)})):self.postMessage([a,b,c])}
var ic={b:(a,b,c,d)=>Fa(`Assertion failed: ${J(a)}, at: `+[b?J(b):"unknown filename",c,d?J(d):"unknown function"]),c:(a,b,c)=>{var d=new Sa(a);F()[d.ca+16>>2]=0;F()[d.ca+4>>2]=b;F()[d.ca+8>>2]=c;Ta=a;Ua++;throw Ta;},L:()=>Fa(""),q:(a,b,c)=>{b=K(b);O(a,{name:b,fromWireType:d=>d,toWireType:function(d,e){if("bigint"!=typeof e&&"number"!=typeof e)throw new TypeError(`Cannot convert "${Va(e)}" to ${this.name}`);"number"==typeof e&&(e=BigInt(e));return e},ka:8,readValueFromPointer:$a(b,c,-1==b.indexOf("u")),
ia:null})},P:(a,b,c,d)=>{b=K(b);O(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,f){return f?c:d},ka:8,readValueFromPointer:function(e){return this.fromWireType(w()[e])},ia:null})},o:(a,b,c,d,e,f,g,h,k,m,l,r,q)=>{l=K(l);f=Q(e,f);h&&=Q(g,h);m&&=Q(k,m);q=Q(r,q);var v=jb(l);ib(v,function(){Cb(`Cannot construct ${l} due to unbound types`,[d])});S([a,b,c],d?[d]:[],t=>{t=t[0];if(d){var z=t.ba;var X=z.na}else X=eb.prototype;t=fb(l,function(...Ma){if(Object.getPrototypeOf(this)!==Na)throw new N(`Use 'new' to construct ${l}`);
if(void 0===E.ma)throw new N(`${l} has no accessible constructor`);var yb=E.ma[Ma.length];if(void 0===yb)throw new N(`Tried to invoke ctor of ${l} with invalid number of parameters (${Ma.length}) - expected (${Object.keys(E.ma).toString()}) parameters instead!`);return yb.apply(this,Ma)});var Na=Object.create(X,{constructor:{value:t}});t.prototype=Na;var E=new kb(l,t,Na,q,z,f,h,m);if(E.ha){var Y;(Y=E.ha).za??(Y.za=[]);E.ha.za.push(E)}z=new wb(l,E,!0,!1,!1);Y=new wb(l+"*",E,!1,!1,!1);X=new wb(l+" const*",
E,!1,!0,!1);gb[a]={pointerType:Y,Ca:X};xb(v,t);return[z,Y,X]})},i:(a,b,c,d,e,f)=>{var g=Db(b,c);e=Q(d,e);S([],[a],h=>{h=h[0];var k=`constructor ${h.name}`;void 0===h.ba.ma&&(h.ba.ma=[]);if(void 0!==h.ba.ma[b-1])throw new N(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${h.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);h.ba.ma[b-1]=()=>{Cb(`Cannot construct ${h.name} due to unbound types`,g)};
S([],g,m=>{m.splice(1,0,null);h.ba.ma[b-1]=Gb(k,m,null,e,f);return[]});return[]})},f:(a,b,c,d,e,f,g,h,k)=>{var m=Db(c,d);b=K(b);b=Hb(b);f=Q(e,f);S([],[a],l=>{function r(){Cb(`Cannot call ${q} due to unbound types`,m)}l=l[0];var q=`${l.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);h&&l.ba.Ja.push(b);var v=l.ba.na,t=v[b];void 0===t||void 0===t.fa&&t.className!==l.name&&t.qa===c-2?(r.qa=c-2,r.className=l.name,v[b]=r):(hb(v,b,q),v[b].fa[c-2]=r);S([],m,z=>{z=Gb(q,z,l,f,g,k);void 0===v[b].fa?
(z.qa=c-2,v[b]=z):v[b].fa[c-2]=z;return[]});return[]})},N:a=>O(a,Jb),G:(a,b,c,d)=>{function e(){}b=K(b);e.values={};O(a,{name:b,constructor:e,fromWireType:function(f){return this.constructor.values[f]},toWireType:(f,g)=>g.value,ka:8,readValueFromPointer:Kb(b,c,d),ia:null});ib(b,e)},j:(a,b,c)=>{var d=Lb(a);b=K(b);a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:fb(`${d.name}_${b}`,function(){})}});a.values[c]=d;a[b]=d},p:(a,b,c)=>{b=K(b);O(a,{name:b,fromWireType:d=>
d,toWireType:(d,e)=>e,ka:8,readValueFromPointer:Mb(b,c),ia:null})},M:(a,b,c,d,e,f,g)=>{var h=Db(b,c);a=K(a);a=Hb(a);e=Q(d,e);ib(a,function(){Cb(`Cannot call ${a} due to unbound types`,h)},b-1);S([],h,k=>{xb(a,Gb(a,[k[0],null].concat(k.slice(1)),null,e,f,g),b-1);return[]})},h:(a,b,c,d,e)=>{b=K(b);-1===e&&(e=4294967295);e=h=>h;if(0===d){var f=32-8*c;e=h=>h<<f>>>f}var g=b.includes("unsigned")?function(h,k){return k>>>0}:function(h,k){return k};O(a,{name:b,fromWireType:e,toWireType:g,ka:8,readValueFromPointer:$a(b,
c,0!==d),ia:null})},d:(a,b,c)=>{function d(f){var g=F()[f>>2];f=F()[f+4>>2];return new e(xa().buffer,f,g)}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=K(c);O(a,{name:c,fromWireType:d,ka:8,readValueFromPointer:d},{Ha:!0})},O:(a,b)=>{b=K(b);O(a,{name:b,fromWireType:function(c){for(var d=F()[c>>2],e=c+4,f,g=e,h=0;h<=d;++h){var k=e+h;if(h==d||0==w()[k])g=J(g,k-g),void 0===f?f=g:(f+=String.fromCharCode(0),f+=g),g=
k+1}R(c);return f},toWireType:function(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new N("Cannot pass non-string to std::string");var f=e?V(d):d.length;var g=u(4+f+1),h=g+4;F()[g>>2]=f;e?U(d,h,f+1):w().set(d,h);null!==c&&c.push(R,g);return g},ka:8,readValueFromPointer:qb,ia(c){R(c)}})},m:(a,b,c)=>{c=K(c);if(2===b){var d=Pb;var e=Qb;var f=Rb;var g=h=>za()[h>>1]}else 4===b&&(d=Sb,e=Tb,f=Ub,g=h=>F()[h>>2]);
O(a,{name:c,fromWireType:h=>{for(var k=F()[h>>2],m,l=h+4,r=0;r<=k;++r){var q=h+4+r*b;if(r==k||0==g(q))l=d(l,q-l),void 0===m?m=l:(m+=String.fromCharCode(0),m+=l),l=q+b}R(h);return m},toWireType:(h,k)=>{if("string"!=typeof k)throw new N(`Cannot pass non-string to C++ string type ${c}`);var m=f(k),l=u(4+m+b);F()[l>>2]=m/b;e(k,l+4,m+b);null!==h&&h.push(R,l);return l},ka:8,readValueFromPointer:qb,ia(h){R(h)}})},Q:(a,b)=>{b=K(b);O(a,{Oa:!0,name:b,ka:0,fromWireType:()=>{},toWireType:()=>{}})},E:(a,b)=>{let c;
c=Vb[Wb]=new Worker(Xb);c.postMessage({$ww:Wb,wasm:ma,js:n.mainScriptUrlOrBlob||_scriptName,wasmMemory:A,sb:a,sz:b});c.onmessage=Ea;return Wb++},s:()=>{},t:(a,b)=>{W[a]&&(clearTimeout(W[a].id),delete W[a]);if(!b)return 0;var c=setTimeout(()=>{delete W[a];La(()=>hc(a,performance.now()))},b);W[a]={id:c,Ra:b};return 0},H:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();var g=Math.max(f,e);F()[a>>2]=60*g;D()[b>>2]=Number(f!=e);
b=h=>{var k=Math.abs(h);return`UTC${0<=h?"-":"+"}${String(Math.floor(k/60)).padStart(2,"0")}${String(k%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(U(a,c,17),U(b,d,17)):(U(a,d,17),U(b,c,17))},A:(a,b)=>w().set(Z[a].Ea,b),y:()=>Yb.length,z:()=>Z.length,w:(a,b)=>{a=Yb[a].Na;U(a,b,V(a)+1)},u:a=>Z[a].mode,B:a=>Z[a].Ea.length,x:(a,b)=>{a=Yb[a].Pa;U(a,b,V(a)+1)},v:(a,b)=>{a=Z[a].Qa;U(a,b,V(a)+1)},D:()=>{a:{if(!Zb.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),
null!==a&&(a+="\n"));if(!a){var b=null;break a}b=Array(V(a)+1);a=Nb(a,b,0,b.length);b.length=a;Zb=b}b=Zb.shift()}return"number"===typeof b?b:-1},R:a=>{console.error(J(a))},T:a=>{console.log(J(a))},S:a=>{console.warn(J(a))},e:()=>Date.now(),k:a=>y(J(a)),l:()=>performance.now(),C:a=>la(J(a)),I:a=>{var b=w().length;a>>>=0;if(a<=b||2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-A.buffer.byteLength+
65535)/65536|0;try{A.grow(d);C();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},J:(a,b)=>{var c=0,d=0,e;for(e of bc()){var f=b+c;F()[a+d>>2]=f;c+=U(e,f,Infinity)+1;d+=4}return 0},K:(a,b)=>{var c=bc();F()[a>>2]=c.length;a=0;for(var d of c)a+=V(d)+1;F()[b>>2]=a;return 0},n:a=>{throw new Ka(a);},g:gc,a:A,r:a=>{throw new Ka(a);},F:(a,b)=>{dc(w().subarray(a,a+b));return 0},U:function(a,b){for(let c of Object.values(Vb))c.postMessage({_wsc:a,x:[b]}),c.onmessage=d=>gc(...d.data)}},G=await (async function(){function a(d,
e){G=d.exports;Pa=G.Z;ma=e;H--;0==H&&I&&(d=I,I=null,d());return G}H++;var b={a:ic};if(n.instantiateWasm)return new Promise(d=>{n.instantiateWasm(b,(e,f)=>{d(a(e,f))})});Ga??=x+"Vosklet.wasm";try{var c=await Ja(b);return a(c.instance,c.module)}catch(d){return ba(d),Promise.reject(d)}}()),R=G.W,u=G.X,Ab=G.Y,hc=G._,Ba=G.$;function jc(){0<H?I=jc:fa?(aa(n),Aa()):0<H?I=jc:(n.calledRun=!0,na||(Aa(),aa(n)))}jc();moduleRtn=ca;


  return moduleRtn;
}
);
})();
if (typeof exports === 'object' && typeof module === 'object') {
  module.exports = loadVosklet;
  // This default export looks redundant, but it allows TS to import this
  // commonjs style module.
  module.exports.default = loadVosklet;
} else if (typeof define === 'function' && define['amd'])
  define([], () => loadVosklet);
